### ISSUE TITLE
Feature : Use custom shader with more than one texture sample at the time

### ISSUE THREAD

**Issue by Fraggle** [CatalystApps/StarlingGAFPlayer#27]
Hello,

One of our animation ends up with 9 atlases (i know it's a lot). Our draw calls are going through the roof but I was wondering if you could uses a custom shader than use more than one sample and batch everything together in one draw call.

What do you think about that ?

**Comment by ivanavdieienko** [comment]
Hello.
Now we can not make custom renderers due to Starling limitations. We are waiting for this (https://github.com/Gamua/Starling-Framework/issues/619) issue. When it'll be done we'll be able to implement it. For some known reasons we can't modify Starling sources. But if you really need such a feature you can do it by yourself. Sources of Starling Framework and Starling GAF library are available to fork and modify.

**Comment by Fraggle** [comment]
Yeah, you're right, actually I started a thread on starling forum and general consensus is that it will not necessary be better.

**Comment by Fraggle** [comment]
Well, actually, you could handle the rendering of the whole GAFMovieClip yourself in a custom display object. You would lose the automatic batching from starling but you could optimise you rendering quite a lot by going in that direction (using your own static vertex buffer etc..).
That's the way they do it in Spine and their runtime performances are very high because of that.

**Comment by Fraggle** [comment]
Not longer working on Gaf
